// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAR4FCmsLv2N5tgdBoghHxHeKVTf8cSX-Y',
    appId: '1:85913817959:android:bd559078ea1dc31759d5c2',
    messagingSenderId: '85913817959',
    projectId: 'hospital-locator-india',
    databaseURL: 'https://hospital-locator-india-default-rtdb.firebaseio.com',
    storageBucket: 'hospital-locator-india.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWen-Z_fQC7-aFqB3Ubzz_kjwibG6OI8E',
    appId: '1:85913817959:ios:c152c4d1a342250759d5c2',
    messagingSenderId: '85913817959',
    projectId: 'hospital-locator-india',
    databaseURL: 'https://hospital-locator-india-default-rtdb.firebaseio.com',
    storageBucket: 'hospital-locator-india.appspot.com',
    iosBundleId: 'com.example.hospitalFinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWen-Z_fQC7-aFqB3Ubzz_kjwibG6OI8E',
    appId: '1:85913817959:ios:c152c4d1a342250759d5c2',
    messagingSenderId: '85913817959',
    projectId: 'hospital-locator-india',
    databaseURL: 'https://hospital-locator-india-default-rtdb.firebaseio.com',
    storageBucket: 'hospital-locator-india.appspot.com',
    iosBundleId: 'com.example.hospitalFinder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHLz9iLzfF-uoD5Fh8rL2SPHPxk47gd1o',
    appId: '1:85913817959:web:d96b987b8de5b6ac59d5c2',
    messagingSenderId: '85913817959',
    projectId: 'hospital-locator-india',
    authDomain: 'hospital-locator-india.firebaseapp.com',
    databaseURL: 'https://hospital-locator-india-default-rtdb.firebaseio.com',
    storageBucket: 'hospital-locator-india.appspot.com',
    measurementId: 'G-8ETP2M9TE3',
  );

}